BB_DATA_PATH_PREFIX = "./data/big-bucket"
BB_SCALED_IMAGE_DATA_PATH = BB_DATA_PATH_PREFIX + "/scaled-image-data"
BB_FOURIER_TRANSFORMED_DATA_PATH = BB_DATA_PATH_PREFIX + "/fourier-transformed-data"
BB_WAVELET_TRANSFORMED_DATA_PATH = BB_DATA_PATH_PREFIX + "/wavelet-transformed-data"
BB_FOURIER_WAVELET_TRANSFORMED_DATA_PATH = BB_DATA_PATH_PREFIX + "/fourier-transformed-wavelet-data"
BB_POSITIVE_EXAMPLES_PATH = BB_DATA_PATH_PREFIX + "/positive-examples"
BB_NEGATIVE_EXAMPLES_PATH = BB_DATA_PATH_PREFIX + "/negative-examples"

SB_DATA_PATH_PREFIX = "./data/small-bucket"
SB_SCALED_IMAGE_DATA_PATH = SB_DATA_PATH_PREFIX + "/scaled-image-data"
SB_FOURIER_TRANSFORMED_DATA_PATH = SB_DATA_PATH_PREFIX + "/fourier-transformed-data"
SB_WAVELET_TRANSFORMED_DATA_PATH = SB_DATA_PATH_PREFIX + "/wavelet-transformed-data"
SB_FOURIER_WAVELET_TRANSFORMED_DATA_PATH = SB_DATA_PATH_PREFIX + "/fourier-transformed-wavelet-data"
SB_POSITIVE_EXAMPLES_PATH = SB_DATA_PATH_PREFIX + "/positive-examples"
SB_NEGATIVE_EXAMPLES_PATH = SB_DATA_PATH_PREFIX + "/negative-examples"

WAVELET_TRANSFORM = 'wavelet'
FOURIER_TRANSFORM = 'fourier'
FOURIER_AND_WAVELET_TRANSFORM = 'wavelet-fourier'
UNTRANSFORMED = 'no-transform'

SMALL_BUCKET = 'small'
BIG_BUCKET = 'big'

DATA_TYPE_DICT = {
    BB_WAVELET_TRANSFORMED_DATA_PATH: WAVELET_TRANSFORM,
    BB_FOURIER_TRANSFORMED_DATA_PATH: FOURIER_TRANSFORM,
    BB_FOURIER_WAVELET_TRANSFORMED_DATA_PATH: FOURIER_AND_WAVELET_TRANSFORM,
    BB_SCALED_IMAGE_DATA_PATH: UNTRANSFORMED,
    SB_WAVELET_TRANSFORMED_DATA_PATH: WAVELET_TRANSFORM,
    SB_FOURIER_TRANSFORMED_DATA_PATH: FOURIER_TRANSFORM,
    SB_FOURIER_WAVELET_TRANSFORMED_DATA_PATH: FOURIER_AND_WAVELET_TRANSFORM,
    SB_SCALED_IMAGE_DATA_PATH: UNTRANSFORMED,
}

SB_DATA_TYPE_DICT = {
    WAVELET_TRANSFORM: SB_WAVELET_TRANSFORMED_DATA_PATH,
    FOURIER_TRANSFORM: SB_FOURIER_TRANSFORMED_DATA_PATH,
    UNTRANSFORMED: SB_SCALED_IMAGE_DATA_PATH,
    FOURIER_AND_WAVELET_TRANSFORM: SB_FOURIER_WAVELET_TRANSFORMED_DATA_PATH
}

BB_DATA_TYPE_DICT = {
    WAVELET_TRANSFORM: BB_WAVELET_TRANSFORMED_DATA_PATH,
    FOURIER_TRANSFORM: BB_FOURIER_TRANSFORMED_DATA_PATH,
    UNTRANSFORMED: BB_SCALED_IMAGE_DATA_PATH,
    FOURIER_AND_WAVELET_TRANSFORM: BB_FOURIER_WAVELET_TRANSFORMED_DATA_PATH
}


IMAGE_HEIGHT = 3000
IMAGE_WIDTH = 4000
RESIZED_HEIGHT = 450
RESIZED_WIDTH = 600

NEG = 0
POS = 1
